### ISSUE TITLE
Internal security/correctness review of the Orchard Action circuit implementation and docs

### ISSUE THREAD

**Issue by daira** [zcash/orchard#83]
The PRs implementing the circuit have been / are being reviewed individually, but this PR-based review process leaves potential gaps, because code changed in a PR often has interdependencies with code that hasn't changed.

We need to have another pass over the whole implementation, checking consistency with the Orchard book, the spec, and the intended design in our heads.

**Comment by daira** [comment]
* [ ] Fixed-base full width scalar multiplication
* [ ] Fixed-base signed 64-bit scalar multiplication
* [ ] Variable-base scalar multiplication
* [ ] Complete point addition
* [ ] Sinsemilla hash
* [ ] Sinsemilla NoteCommit
* [ ] Sinsemilla Commit<sup>ivk</sup>
* [ ] Pedersen value commitments
* [ ] Poseidon hash/PRF
* [ ] Nullifier derivation
* [ ] Merkle path validation
* [ ] enableSpends/enableOutputs checks
* [ ] High-level statement

**Comment by str4d** [comment]
Stealing @daira's list above for my own review (#318):

* ECC:
  * [ ] Fixed-base full width scalar multiplication
  * [ ] Fixed-base signed 64-bit scalar multiplication
  * [ ] Variable-base scalar multiplication
  * [ ] Complete point addition
* [ ] Range checks
* Sinsemilla:
  * [ ] Sinsemilla hash
  * [ ] Sinsemilla NoteCommit
  * [ ] Sinsemilla Commit<sup>ivk</sup>
* [ ] Pedersen value commitments
* [ ] Poseidon hash/PRF
* [x] Nullifier derivation
* [ ] Merkle path validation
* [x] enableSpends/enableOutputs checks
* [ ] Inputization
* [x] High-level statement

**Comment by str4d** [comment]
I have reviewed everything I wanted to. (I implemented Poseidon, so I did not review it; others have.)
